### PR TITLE
Add glib to host deps to build gts stuff + add ffmpeg

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
Something else that I noticed is missing is ffmpeg, but probably that is not strictly necessary for gazebo.

**Comment by Tobias-Fischer** [comment]
Thanks for the hint - I added it and it seems to work :+1:

**Comment by Tobias-Fischer** [comment]
Fix #15

**Comment by Tobias-Fischer** [comment]
@seanyen - all green, this is ready to be merged

**Comment by traversaro** [comment]
The regression fixed by this PR was catched also by my CI in https://github.com/robotology/robotology-superbuild/runs/1356099458 :

~~~
CMake Error at /usr/share/miniconda/envs/test/share/cmake-3.18/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "Findignition-common3-graphics.cmake" in CMAKE_MODULE_PATH
  this project has asked CMake to find a package configuration file provided
  by "ignition-common3-graphics", but CMake did not find one.

  Could not find a package configuration file provided by
  "ignition-common3-graphics" (requested version 3.7.0) with any of the
  following names:

    ignition-common3-graphicsConfig.cmake
    ignition-common3-graphics-config.cmake

  Add the installation prefix of "ignition-common3-graphics" to
  CMAKE_PREFIX_PATH or set "ignition-common3-graphics_DIR" to a directory
  containing one of the above files.  If "ignition-common3-graphics" provides
  a separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  /usr/share/miniconda/envs/test/lib/cmake/ignition-common3/ignition-common3-config.cmake:193 (find_dependency)
  /usr/share/miniconda/envs/test/lib/cmake/gazebo/gazebo-config.cmake:209 (find_package)
  cmake/BuildGazeboYARPPlugins.cmake:31 (find_package)
  build/install/share/YCM/modules/FindOrBuildPackage.cmake:215 (include)
  CMakeLists.txt:136 (find_or_build_package)
~~~

It would be nice to have some option in ignition-cmake upstream to have a clear error if the dependency of some components are missing instead of silently disabling the component, see https://github.com/ignitionrobotics/ign-cmake/issues/63 .

**Review by traversaro — APPROVED** [review]

**Comment by Tobias-Fischer** [comment]
Here we also have the chance to test whether the library was created - feel free to add these tests @traversaro

**Comment by traversaro** [comment]
Good point!

**Pull request merged**
