### PR TITLE
Bump build num to pull in tinyxml 9

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
https://github.com/conda-forge/libignition-gui-feedstock/pull/4 fails because:
```
mamba create -n test libignition-cmake2 libprotobuf=3.16 tinyxml2 ogre=1.12 libignition-math6  libignition-common4 libignition-plugin1 libignition-transport10 libignition-rendering5 libignition-msgs7 libignition-tools1 libignition-utils1 qt xorg-libxfixes

Encountered problems while solving:
  - package libignition-common4-4.0.0-h4b9f6df_0 requires tinyxml2 >=8.0.0,<8.1.0a0, but none of the providers can be installed
```

Some other packages are built with tinyxml 9, so let's pull that in.

**Comment by Tobias-Fischer** [comment]
tinyxml2=9 is pulled in as desired ..

/cc @traversaro @wolfv - we might also need to rebuild libsdformat.

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
For reference, the ABI of tinyxml2 was bumped in https://github.com/conda-forge/tinyxml2-feedstock/pull/9 . Given the number of repos that now depend on tinyxml2, for the next ABI change it could make sense to try to add an organize migration in https://github.com/conda-forge/conda-forge-pinning-feedstock . I watched  https://github.com/conda-forge/tinyxml2-feedstock for now, I will try to remember this when a new version come out.

**Pull request merged**
