### PR TITLE
Only depend on libuuid on Linux

### PR DESCRIPTION
**Pull request by traversaro**
As on macOS the libuuid dependency can create conflicts, see https://github.com/conda-forge/libignition-cmake0-feedstock/pull/7 and https://github.com/conda-forge/libuuid-feedstock/issues/16 .

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
I was a bit too optimistic on the CDN propagation times, so to trigger new builds I took the occasion to cleanup a bit the dependencies, in particular removing the explicit `run` dependencies from the package that properly contain `run_exports` . I hope this is ok.

**Comment by traversaro** [comment]
The CDN propagated the change in https://github.com/conda-forge/libignition-cmake0-feedstock/pull/7 and now the builds passes.

**Comment by Tobias-Fischer** [comment]
Great work, thanks @traversaro

**Pull request merged**
