### PR TITLE
add tinyxml to libignition common

### PR DESCRIPTION
**Pull request by wolfv**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by seanyen** [comment]
@wolfv LGTM, and can you bump the build number? I cannot edit it on the fly.

**Comment by wolfv** [comment]
turns out that tinyxml2 doesn't have a run exports and a new version was just released ... :) we'll have to rebuild a couple of packages I am afraid 
btw I am working on getting Gazebo 11 to build on Linux... almost there...

**Comment by wolfv** [comment]
would be cool if you can merge this now @seanyen then I can try the gazebo 11 build for linux.

**Comment by wolfv** [comment]
then we can move all our deps to tinyxml 8

**Pull request merged**
